### ISSUE TITLE
Remove command icon

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5-remove-format#3]
We need a nice icon for the feature. In the initial rollout I used erase icon that could be reused (actually font/bg color will reuse it too).

![Remove format icon preview](https://user-images.githubusercontent.com/5353898/55095912-3df2b980-50b9-11e9-83f7-f2582c01354a.png)

What do you think about the icon? Do we want to add a new one or  is it ok to reuse the existing one?

**Comment by oleq** [comment]
This needs a research. We need to come up with an icon the users are familiar with, preferably the most common among the word processors.

**Comment by dkonopka** [comment]
I've made a quick research, which says that almost everyone is using **`T`** with **`×`** sign (or strikethrough in GDocs case).

FYI: This **`A`** with rubber is a Word usage.

![formatting-icon](https://user-images.githubusercontent.com/10219857/55160346-66cf8900-5163-11e9-8e4c-6107e94b9353.jpg)

I'll propose something for CK5 soon.

**Comment by oleq** [comment]
Part of now https://github.com/ckeditor/ckeditor5-remove-format/pull/1.
