### ISSUE TITLE
getAttributeProperties is not a function

### ISSUE THREAD

**Issue by deonclem** [ckeditor/ckeditor5-remove-format#8]
I'm trying to use this plugin and added it to my custom build but I'm getting the following error whenever I'm trying to render something with any style or to apply any style to an element:

```js
ckeditor.component.ts:266 TypeError: e.getAttributeProperties is not a function
    at Yb._getFormattingAttributes (ckeditor.js:5)
    at _getFormattingAttributes.next (<anonymous>)
    at Au (ckeditor.js:5)
    at n (ckeditor.js:5)
    at Yb._getFormattingItems (ckeditor.js:5)
    at _getFormattingItems.next (<anonymous>)
    at Au (ckeditor.js:5)
    at Yb.refresh (ckeditor.js:5)
    at Ec.<anonymous> (ckeditor.js:5)
    at Ec.fire (ckeditor.js:5)
```

Thew from `_getFormattingAttributes` .

But then I found https://github.com/ckeditor/ckeditor5-engine/pull/1711, I reckon the plugin relies on it?
Do I have to wait until the next CKE5 major release to use it?

Thanks!

**Comment by ma2ciek** [comment]
Hi @deonclem 

> Do I have to wait until the next CKE5 major release to use it?

Yep, you should wait for the nest release to use all features or build CKEditor 5 from GH masters (I'd recommend the first approach as it's much easier to build CKEditor 5 from NPM than from GH sourcecode and the editor will be stable.)

**Comment by deonclem** [comment]
Thanks for the quick reply. Any idea if there's an official "Release Schedule" somewhere or info about when the next one is going to happen?

**Comment by Reinmar** [comment]
We don't have such a place yet (it'd be good idea to create it). But I can tell here that we plan to release the new features next week :).
